version: "3.9"

services:
  db:
    image: postgis/postgis
    restart: always
    ports:
      - 5432:5432
    shm_size: 128mb
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - ./data/db:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  file-server:
    image: busybox
    ports: 
      - 3001:3001
    volumes:
      - ./data/uploads:/www
    command: busybox httpd -f -v -p 3001 -h /www

